function initpgaz_gui
    displayInfo();

    screenSize = get(0, 'ScreenSize');
    guiWidth = 400;
    guiHeight = 240;
    guiX = (screenSize(3) - guiWidth) / 2;
    guiY = (screenSize(4) - guiHeight) / 2;

    fig = figure('Name', 'PGAz', ...
                 'NumberTitle', 'off', ...
                 'MenuBar', 'none', ...
                 'Resize', 'off', ...
                 'Position', [guiX, guiY, guiWidth, guiHeight], ...
                 'Color', [1, 1, 1]);

    imageFolder = fullfile(pwd, 'pgaz_images');
    imageFile = 'pgaz_logo.png';
    imagePath = fullfile(imageFolder, imageFile);

    if exist(imagePath, 'file')
        ax = axes('Parent', fig, ...
                  'Units', 'pixels', ...
                  'Position', [95, 90, 210, 160]);
        img = imread(imagePath);
        imshow(img, 'Parent', ax);
    else
        warning('The image file "%s" was not found in the folder "%s" (Current Folder: %s).', ...
                imageFile, imageFolder, pwd);
    end

    axesText = axes('Parent', fig, ...
                    'Units', 'pixels', ...
                    'Position', [194, 80, 320, 50], ...
                    'Color', 'none', ...
                    'XColor', 'none', 'YColor', 'none');
    text(0.02, 0.55, 'Power Grid Analyzer', ...
         'FontSize', 20, ...
         'FontWeight', 'bold', ...
         'FontName', 'Times New Roman', ...
         'Color', [0, 0, 0.3], ...
         'HorizontalAlignment', 'center', ...
         'VerticalAlignment', 'middle');
    text(0.018, 0.55, 'Power Grid Analyzer', ...
         'FontSize', 20, ...
         'FontWeight', 'bold', ...
         'FontName', 'Times New Roman', ...
         'Color', [0, 0.3, 0.6], ...
         'HorizontalAlignment', 'center', ...
         'VerticalAlignment', 'middle');

    uicontrol('Style', 'text', ...
              'String', 'version 1.0.0', ...
              'FontSize', 12, ...
              'FontWeight', 'bold', ...
              'FontName', 'Times New Roman', ...
              'ForegroundColor', [1, 0, 0], ...
              'Position', [296, 16, 100, 20], ...
              'BackgroundColor', [1, 1, 1]);

    uicontrol('Style', 'text', ...
              'BackgroundColor', [1, 1, 1], ...
              'Position', [30, 40, 340, 20]);

    progressBar = uicontrol('Style', 'text', ...
                            'BackgroundColor', [1, 0.5, 0], ...
                            'Position', [28, 42, 1, 16]);

    statusText = uicontrol('Style', 'text', ...
                           'String', 'Initializing...', ...
                           'FontSize', 10, ...
                           'FontWeight', 'bold', ...
                           'FontName', 'Times New Roman', ...
                           'ForegroundColor', [0, 0.5, 0], ...
                           'BackgroundColor', [1, 1, 1], ...
                           'HorizontalAlignment', 'center', ...
                           'Position', [30, 70, 340, 15]);

    maxWidth = 370;
    scaleFactor = maxWidth / 100;

    for progress = 0:100
        pause(0.00015);
        newWidth = progress * scaleFactor;
        set(progressBar, 'Position', [16, 42, newWidth, 14]);

        if progress <= 30
            set(statusText, 'String', 'Initializing resources...');
        elseif progress <= 70
            set(statusText, 'String', 'Setting up dependencies...');
        elseif progress <= 90
            set(statusText, 'String', 'Configuring environment...');
        else
            set(statusText, 'String', 'Completing initialization...');
        end

        drawnow;
    end

    set(statusText, 'String', 'System ready. Launching...');
    pause(0.25);
    close(fig);
    pgaz_maingui;
end

function displayInfo()
    info = sprintf(['\n                    < P G A z >\n', ...
                    '    Copyright (C) 2024 Power Grid Analyzer Team\n', ...
                    '                  Version 1.0.0\n', ...
                    '                   July 1, 2024\n\n', ...
                    'Host:       Matlab %s (R%s)\n', ...
                    'Session:    %s\n', ...
                    'Usage:      Graphical User Interface\n', ...
                    'Path:       %s\n'], ...
                    version, version('-release'), datestr(now, 'dd-mmm-yyyy HH:MM:SS'), pwd);
    disp(info);
end
